name: Terraform Apply

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/**'
      - '!**.md'
  workflow_dispatch: {}

defaults:
  run:
    working-directory: infra

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION || 'eu-west-2' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        env:
          TF_VAR_email: "you@example.com"  # set a real email in repo/environ secrets or use tfvars
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        env:
          TF_VAR_email: "you@example.com"
        run: terraform apply -input=false -auto-approve

      - name: CloudFront Invalidation (UI cache bust)
        id: invalidate
        run: |
          DIST_ID=$(terraform output -raw cloudfront_distribution_id)
          echo "Distribution: $DIST_ID"
          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"